#!/usr/bin/env bash
# Configures a new Ubuntu server with a custom HTTP header response.
# shellcheck disable=SC2154

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'

sudo chown -R "$USER":"$USER" /var/www/html
sudo chown -R "$USER":"$USER" /etc/nginx/sites-available/default

touch /var/www/html/index.html
echo 'Hello World!' > /var/www/html/index.html

touch /var/www/html/404.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

echo "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
     add_header  X-Served-By $HOSTNAME;
     root        /var/www/html;
     index       index.html index.htm;
     location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
    
    error_page 404 /404.html;
    location /404 {
      root /var/www/html;
      internal;
    }
}" > /etc/nginx/sites-available/default

sudo service nginx restart
