#!/usr/bin/env bash
# Displays Best School 10 times, but for the 9th iteration.
# Displays Best School and then Hi on a new line.

while ((index < 10))
do
	if ((index == 9))
	then
		echo "Hi"
	fi
	echo "Best School"
	((index++))
done
