#!/usr/bin/env bash
# Install the ufw firewall and setup a few rules on web servers.
# Allows SSH (Port 22), HTTPS (port 443) and HTTP (port 80).

sudo apt install ufw
sudo sed -i 's/IPV6=.*/IPV6=yes/' /etc/default/ufw
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow ssh/tcp
sudo ufw allow https/tcp
sudo ufw allow http/tcp
sudo ufw disable
sudo ufw enable
