#!/usr/bin/env bash
# Fixes a web server to run Nginx as the nginx user listening on port 8080.
pkill apache2
chown nginx:nginx /etc/nginx/nginx.conf
chmod 777 /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo -u nginx service nginx start
